name: Notify to Feishu
description: "Send GitHub event notifications to Feishu (Lark) via webhook"
branding:
  icon: "message-circle"
  color: "blue"

inputs:
  feishu_webhook:
    description: "Feishu webhook URL"
    required: true

runs:
  using: "composite"
  steps:
    - name: Run notification action
      env:
        FEISHU_WEBHOOK: ${{ inputs.feishu_webhook }}
        GITHUB_EVENT_PATH: ${{ github.event_path }}
      run: |
        npm ci
        node dist/index.js --event-type ${{ github.event_name }}
      working-directory: ${{ github.action_path }}
      shell: bash
