name: Notify to Feishu

on:
  pull_request:
    types:
      [
        opened,
        closed,
        reopened,
        ready_for_review,
        review_requested,
        synchronize,
      ]

  issues:
    types: [opened, closed, reopened]

  issue_comment:
    types: [created]

jobs:
  notify:
    runs-on: ubuntu-latest
    if: github.event.pull_request.draft != true
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Print GitHub Event Data
        run: |
          echo "=== GitHub Event Data ==="
          cat $GITHUB_EVENT_PATH
          echo "=== End of Event Data ==="

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Install Dependencies
        run: npm ci

      - name: Build TypeScript
        run: npm run build

      - name: Notify to Feishu
        env:
          FEISHU_WEBHOOK: ${{ secrets.FEISHU_WEBHOOK }}
          GITHUB_EVENT_PATH: ${{ github.event_path }}
        run: npm run handle -- --event-type ${{ github.event_name }}
